hugoblox:
  schema: "2.0"
  identity:
    name: Paolo Chevalier
    type: person
    tagline: Resarch Intern
    description: Last year student in applied mathematics at the National Institute of Applied Sciences (INSA) in France. I mostly have interests in climate science, deep learn
    organization: LSCE (CNRS)
  theme:
    mode: system
    pack: matcha
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    theme_picker: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
    license:
      type: cc
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  seo:
    title: Paolo Chevalier | Research Intern | LSCE
