hugoblox:
  schema: "2.0"
  identity:
    name: Paolo Chevalier
    type: person
    tagline: Resarch Intern
    organization: LSCE (CNRS)
    description: "Paolo Chevalier: Applied Mathematics student at INSA Rennes specializing in AI for climate science and extreme events. See more about me."
  theme:
    mode: system
    pack: matcha
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    theme_picker: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
    license:
      type: cc
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  seo: {}
